baseURL = "http://thomasvanarkel.nl/"
languageCode = "en-gb"
title = "Thomas van Arkel"
googleAnalytics = 'G-Z7VW38YF0T'

theme = "ta-portfolio"

sectionPagesMenu = "main"

[menu]
  [[menu.main]]
    identifier = "themes"
    name = "themes"
    url = "/themes"
    weight = 5
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    url = "/posts"
    weight = 10
  [[menu.main]]
    identifier = "projects"
    name = "projects"
    url = "/projects"
    weight = 20
  [[menu.main]]
    identifier = "publications"
    name = "publications"
    url = "/publications"
    weight = 30
[[menu.main]]
    identifier = "tools"
    name = "tools"
    url = "/tools"
    weight = 40
